Repository YAPP-Github/20th-iOS-Team-2-FE, pull requests merged in 2022-07, with the labels that each got.

#52 [FEAT] 일정 List Pager 적용
  Sofa.xcodeproj/project.pbxproj
  Sofa.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Sofa/Sources/View/Home/HomeView.swift
  Sofa/Sources/View/Home/SubViews/EventList.swift
  Sofa/Sources/View/Home/SubViews/Row/EventRow.swift
Labels: 🏠 홈

#53 [FEAT] Chat Animation (aka.슈슈슉)
  Sofa.xcodeproj/project.pbxproj
  Sofa/Configuration/Mock/ChatInfoMock.json
  Sofa/Sources/Models/FamilyList.swift
  Sofa/Sources/View/Home/SubViews/ChatList.swift
  Sofa/Sources/View/Home/SubViews/Row/ChatRow.swift
  Sofa/Sources/View/Home/ViewModel/ChatViewModel.swift
Labels: 🏠 홈

#55 [FEAT] Apple Login
  Sofa.xcodeproj/project.pbxproj
  Sofa/Configuration/Base/Constants/Constants.swift
  Sofa/Sofa.entitlements
  Sofa/Sources/View/Welcome/LoginSubViews/LoginButtonView.swift
Labels: 🥕 로그인

#58 [FEAT] 날짜 선택 가능한 캘린더 추가
  Sofa.xcodeproj/project.pbxproj
  Sofa.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Sofa/Configuration/Extensions/Ex+View.swift
  Sofa/Sources/Models/CalendarTask.swift
  Sofa/Sources/Models/DateValue.swift
  Sofa/Sources/View/Calendar/CalendarView.swift
  Sofa/Sources/View/Calendar/GeneralDatePickerView.swift
  Sofa/Sources/View/Calendar/SubViews/AppendTaskModalView.swift
  Sofa/Sources/View/Calendar/SubViews/CustomDatePicker.swift
  Sofa/Sources/View/Calendar/SubViews/GeneralCalendar.swift
  Sofa/Sources/View/Calendar/TaskMetaData.swift
Labels: 📅 캘린더

#63 [FEAT] 이미지 상세 화면
  Sofa.xcodeproj/project.pbxproj
  Sofa/Sources/View/Album/AlbumDetailView/AlbumDetailView.swift
  Sofa/Sources/View/Album/AlbumImageDetailView/AlbumImageDetailView.swift
  Sofa/Sources/View/Album/AlbumImageDetailView/SubViews/Blur/Blur.swift
  Sofa/Sources/View/Album/AlbumImageDetailView/SubViews/NavigaionBar/AlbumImageDetailNavigationBar.swift
  Sofa/Sources/View/Album/AlbumImageDetailView/SubViews/SettingBar/AlbumImageDetailSettingBar.swift
  Sofa/Sources/View/Album/AlbumSelectDateView/AlbumSelectDateView.swift
  Sofa/Sources/View/Album/AlbumView.swift
Labels: 🏞 앨범, 🐛Bug

#71 [FEAT] 알림 View UI
  Podfile.lock
  Sofa.xcodeproj/project.pbxproj
  Sofa/Configuration/Extensions/Ex+UINavigationController.swift
  Sofa/Configuration/Extensions/Ex+View.swift
  Sofa/Sources/View/ContentView.swift
  Sofa/Sources/View/Home/HomeView.swift
  Sofa/Sources/View/Home/ModalView.swift
  Sofa/Sources/View/Home/NotificationView.swift
  Sofa/Sources/View/Home/SubViews/HomeNavigationBarStyle.swift
  Sofa/Sources/View/Home/SubViews/LabelView.swift
  Sofa/Sources/View/Home/ViewModel/EventViewModel.swift
Labels: 🏠 홈

#69 [FEAT] 이미지 다운로드
  Sofa.xcodeproj/project.pbxproj
  Sofa/Configuration/ViewModifiers/ToastMessage.swift
  Sofa/Sources/View/Album/AlbumCommentView/AlbumCommentView.swift
  Sofa/Sources/View/Album/AlbumDetailView/AlbumDetailView.swift
  Sofa/Sources/View/Album/AlbumImageDetailView/AlbumImageDetailView.swift
  Sofa/Sources/View/Album/AlbumPhotoAddView/AlbumPhotoAddView.swift
Labels: 🏞 앨범

#73 [FEAT] 일정 상세뷰 UI 구현
  Sofa.xcodeproj/project.pbxproj
  Sofa/Sources/View/Calendar/CalendarView.swift
  Sofa/Sources/View/Calendar/SubViews/CustomDatePicker.swift
  Sofa/Sources/View/Calendar/SubViews/TaskDetailView.swift
Labels: 📅 캘린더

#75 [FEAT] 알림 View & 일정 View Tab 이동
  Sofa.xcodeproj/project.pbxproj
  Sofa/Configuration/Mock/NotificationMock.json
  Sofa/Sources/Models/Notifications.swift
  Sofa/Sources/View/ContentView.swift
  Sofa/Sources/View/Home/HomeView.swift
  Sofa/Sources/View/Home/NotificationView.swift
  Sofa/Sources/View/Home/SubViews/EventList.swift
  Sofa/Sources/View/Home/SubViews/Row/EventRow.swift
  Sofa/Sources/View/Home/ViewModel/NotificationViewModel.swift
Labels: 🏠 홈

#76 [FEAT] 앨범 댓글 UI
  Sofa.xcodeproj/project.pbxproj
  Sofa/Configuration/Base/Constants/Constants.swift
  Sofa/Configuration/Extensions/Ex+String.swift
  Sofa/Configuration/Mock/CommentMock.json
  Sofa/Sources/Models/Comment.swift
  Sofa/Sources/View/Album/AlbumCommentView/AlbumCommentView.swift
  Sofa/Sources/View/Album/AlbumCommentView/SubViews/CommentModal/CommentModal.swift
  Sofa/Sources/View/Album/AlbumCommentView/SubViews/CommentModal/ModalBackGround.swift
  Sofa/Sources/View/Album/AlbumCommentView/SubViews/Row/AlbumCommentList.swift
  Sofa/Sources/View/Album/AlbumCommentView/SubViews/Row/AlbumCommentRow.swift
  Sofa/Sources/View/Album/AlbumCommentView/SubViews/ViewModel/CommentViewModel.swift
  Sofa/Sources/View/Album/AlbumDetailView/AlbumDetailView.swift
  Sofa/Sources/View/Album/AlbumDetailView/SubViews/Row/AlbumDetailRow.swift
  Sofa/Sources/View/Album/AlbumImageDetailView/AlbumImageDetailView.swift
  Sofa/Sources/View/Album/AlbumPhotoAddView/AlbumPhotoAddView.swift
  Sofa/Sources/View/Album/AlbumPhotoAddView/SubViews/ZoomScrollView/ZoomScrollView.swift
  Sofa/Sources/View/Album/AlbumSelectDateView/AlbumSelectDateView.swift
  Sofa/Sources/View/Album/AlbumView.swift
  Sofa/Sources/View/Album/SubViews/ActionSheet/AlbumActionSheetCard.swift
  Sofa/Sources/View/Album/SubViews/ActionSheet/GreyOutOfFocusView.swift
Labels: 🏞 앨범

#81 [CHORE] 권한 설정, Navigation bar bug 수정
  Sofa.xcodeproj/project.pbxproj
  Sofa/Sources/View/Album/AlbumPhotoAddView/AlbumPhotoAddView.swift
  Sofa/Sources/View/Album/AlbumPhotoAddView/SubViews/Row/AlbumPhotoAddList.swift
  Sofa/Sources/View/Album/AlbumPhotoAddView/SubViews/Row/AlbumPhotoLibrary.swift
  Sofa/Sources/View/Album/AlbumRecordAddView/AlbumRecordAddView.swift
  Sofa/Sources/View/Album/AlbumRecordAddView/SubViews/AudioBar/AudioBarView.swift
  Sofa/Sources/View/Album/AlbumRecordAddView/SubViews/NavigationBar/AlbumRecordAddNavigationBar.swift
  Sofa/Sources/View/Album/AlbumRecordAddView/SubViews/NavigationBar/NavigationBarOnlyCancelButtonStyle.swift
  Sofa/Sources/View/Album/AlbumRecordAddView/SubViews/ViewModel/AudioRecorderViewModel.swift
  Sofa/Sources/View/Album/AlbumSelectDateView/AlbumSelectDateView.swift
  Sofa/Sources/View/Album/AlbumSelectDateView/SubViews/ViewModel/AudioRecorderURLViewModel.swift
  Sofa/Sources/View/Album/AlbumView.swift
Labels: 🏞 앨범, 🐛Bug

#82 [FEAT] 회원가입 UI
  Sofa.xcodeproj/project.pbxproj
  Sofa/Configuration/Assets/Assets.xcassets/alert.imageset/Contents.json
  Sofa/Configuration/Assets/Assets.xcassets/alert.imageset/alert.png
  Sofa/Configuration/Assets/Assets.xcassets/alert.imageset/alert@2x.png
  Sofa/Configuration/Assets/Assets.xcassets/alert.imageset/alert@3x.png
  Sofa/Configuration/Assets/Assets.xcassets/cta.imageset/Contents.json
  Sofa/Configuration/Assets/Assets.xcassets/cta.imageset/cta.png
  Sofa/Configuration/Assets/Assets.xcassets/cta.imageset/cta@2x.png
  Sofa/Configuration/Assets/Assets.xcassets/cta.imageset/cta@3x.png
  Sofa/Configuration/Assets/Assets.xcassets/goRoomBtn.imageset/Contents.json
  Sofa/Configuration/Assets/Assets.xcassets/goRoomBtn.imageset/goRoomBtn.png
  Sofa/Configuration/Assets/Assets.xcassets/goRoomBtn.imageset/goRoomBtn@2x.png
  Sofa/Configuration/Assets/Assets.xcassets/goRoomBtn.imageset/goRoomBtn@3x.png
  Sofa/Configuration/Assets/Assets.xcassets/linkBtn.imageset/Contents.json
  Sofa/Configuration/Assets/Assets.xcassets/linkBtn.imageset/linkBtn.png
  Sofa/Configuration/Assets/Assets.xcassets/linkBtn.imageset/linkBtn@2x.png
  Sofa/Configuration/Assets/Assets.xcassets/linkBtn.imageset/linkBtn@3x.png
  Sofa/Configuration/Extensions/Ex+View.swift
  Sofa/Configuration/ViewModifiers/Highlighting.swift
  Sofa/Sources/View/Calendar/CalendarView.swift
  Sofa/Sources/View/Calendar/SubViews/AppendTaskModalView.swift
  Sofa/Sources/View/Calendar/SubViews/TaskDetailView.swift
  Sofa/Sources/View/Home/HomeView.swift
  Sofa/Sources/View/Welcome/RegisterFamilyView.swift
  Sofa/Sources/View/Welcome/RegisterSubViews/GreyOutOfFocusView.swift
  Sofa/Sources/View/Welcome/RegisterSubViews/RegisterFamilyFinishView.swift
  Sofa/Sources/View/Welcome/RegisterSubViews/RegisterFinishView.swift
  Sofa/Sources/View/Welcome/RegisterSubViews/RoleActionSheet.swift
  Sofa/Sources/View/Welcome/RegisterSubViews/RoleActionSheetItem.swift
  Sofa/Sources/View/Welcome/RegisterSubViews/StepCircles.swift
  Sofa/Sources/View/Welcome/RegisterView.swift
  Sofa/Sources/View/Welcome/WelcomeView.swift
Labels: 🌱 회원가입

#83 [FEAT] MessageView Focus 수정 및 Event Row 이벤트처리
  Sofa.xcodeproj/project.pbxproj
  Sofa.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Sofa/Sources/View/Home/HomeView.swift
  Sofa/Sources/View/Home/MessageView.swift
  Sofa/Sources/View/Home/SubViews/EventList.swift
  Sofa/Sources/View/Home/SubViews/Row/EventRow.swift
Labels: 🏠 홈

#85 [CHORE] Tab view
  Sofa/Sources/View/Album/SubViews/Row/AlbumRow.swift
  Sofa/Sources/View/Album/SubViews/Row/AlbumTypeRow.swift
  Sofa/Sources/View/ContentView.swift
  Sofa/Sources/View/Home/MessageView.swift
Labels: 🏠 홈, 📅 캘린더, 🏞 앨범

#86 [CHORE] 배경 흰색 바꾸기
  Sofa/Sources/View/ContentView.swift
Labels: 🏠 홈, 📅 캘린더, 🏞 앨범

#89 [FEAT] 자동로그인 로직 임시 구현
  Sofa/SofaApp.swift
  Sofa/Sources/View/ContentView.swift
  Sofa/Sources/View/Home/HomeView.swift
  Sofa/Sources/View/Home/MessageView.swift
  Sofa/Sources/View/Home/NotificationView.swift
  Sofa/Sources/View/Welcome/LoginSubViews/LoginButtonView.swift
Labels: 🏠 홈, 🥕 로그인

#94 [FEAT] Network 기본 구성 및 예시
  .gitignore
  Podfile
  Podfile.lock
  Sofa.xcodeproj/project.pbxproj
  Sofa/Configuration/Mock/MockData.swift
  Sofa/Sources/Models/Album.swift
  Sofa/Sources/Models/AlbumType.swift
  Sofa/Sources/Network/AlbumManager.swift
  Sofa/Sources/Network/Network.swift
  Sofa/Sources/View/Album/AlbumView.swift
  Sofa/Sources/View/Album/SubViews/Row/AlbumDateRow.swift
  Sofa/Sources/View/Album/SubViews/Row/AlbumList.swift
  Sofa/Sources/View/Album/ViewModel/AlbumListViewModel.swift
Labels: 🏞 앨범

#100 [FEAT] 설정 기본 뷰 구현
  Sofa.xcodeproj/project.pbxproj
  Sofa/Sources/View/Settings/SettingsView.swift
  Sofa/Sources/View/Settings/SubViews/SettingRow.swift
Labels: ⚙️ 설정

#98 [FEAT] 앨범 제목 수정 UI
  Sofa.xcodeproj/project.pbxproj
  Sofa/Configuration/Extensions/Ex+View.swift
  Sofa/Configuration/ViewModifiers/KeyboardHeightHelper.swift
  Sofa/Configuration/ViewModifiers/NavigationBarWithTextButtonStyle.swift
  Sofa/Configuration/ViewModifiers/ToastMessage.swift
  Sofa/Sources/View/Album/AlbumDetailView/AlbumDetailView.swift
  Sofa/Sources/View/Album/AlbumImageDetailView/AlbumImageDetailView.swift
  Sofa/Sources/View/Album/AlbumPhotoAddView/AlbumPhotoAddView.swift
  Sofa/Sources/View/Album/AlbumTitleEditView/AlbumTitleEditView.swift
  Sofa/Sources/View/Album/AlbumTitleEditView/SubViews/NavigationBar/AlbumTitleEditNavigationBar.swift
Labels: 🏞 앨범

#104 [FEAT] 경계선 삭제
  Sofa.xcodeproj/project.pbxproj
  Sofa/Sources/View/Calendar/GeneralDatePickerView.swift
  Sofa/Sources/View/Calendar/SubViews/AppendTaskModalView.swift
  Sofa/Sources/View/Calendar/SubViews/GeneralCalendar.swift
  Sofa/Sources/View/Calendar/SubViews/TaskDetailView.swift
  Sofa/Sources/View/Settings/SubViews/ProfileSettingView.swift
Labels: 📅 캘린더

#105 [CHORE] Home Refactoring
  Sofa/Configuration/Extensions/Ex+Date.swift
  Sofa/Configuration/Extensions/Ex+String.swift
  Sofa/Configuration/Mock/ChatInfoMock.json
  Sofa/Configuration/Mock/HomeInfoMock.json
  Sofa/Sources/Models/FamilyList.swift
  Sofa/Sources/Models/HomeInfo.swift
  Sofa/Sources/View/Home/HomeView.swift
  Sofa/Sources/View/Home/MessageView.swift
  Sofa/Sources/View/Home/SubViews/EventList.swift
  Sofa/Sources/View/Home/SubViews/Row/ChatRow.swift
  Sofa/Sources/View/Home/SubViews/Row/EventRow.swift
Labels: 🏠 홈, 🐛Bug

#107 [FEAT] 녹음 상세 UI
  Sofa.xcodeproj/project.pbxproj
  Sofa/Sources/View/Album/AlbumImageDetailView/AlbumImageDetailView.swift
  Sofa/Sources/View/Album/AlbumImageDetailView/SubViews/SettingBar/AlbumImageDetailSettingBar.swift
  Sofa/Sources/View/Album/AlbumRecordAddView/AlbumRecordAddView.swift
  Sofa/Sources/View/Album/AlbumRecordAddView/SubViews/NavigationBar/AlbumRecordNavigationBar.swift
  Sofa/Sources/View/Album/AlbumRecordDetailView/AlbumRecordDetailView.swift
Labels: 🏞 앨범

#109 [FEAT] Notification UI Detail & MessageView Height 조정
  Sofa.xcodeproj/project.pbxproj
  Sofa/Configuration/Mock/NotificationMock.json
  Sofa/Sources/Models/Notifications.swift
  Sofa/Sources/View/Home/MessageView.swift
  Sofa/Sources/View/Home/NotificationView.swift
  Sofa/Sources/View/Home/SubViews/CustomBoldLabelView.swift
  Sofa/Sources/View/Home/SubViews/LabelView.swift
Labels: 🏠 홈

#114 [FEAT] Login API 연결
  Sofa.xcodeproj/project.pbxproj
  Sofa/Configuration/Base/Constants/Constants.swift
  Sofa/SofaApp.swift
  Sofa/Sources/Models/LoginResponse.swift
  Sofa/Sources/Network/LoginManager.swift
  Sofa/Sources/View/Welcome/LoginSubViews/LoginButtonView.swift
  Sofa/Sources/View/Welcome/LoginSubViews/LoginViewModel/LoginViewModel.swift
  Sofa/Sources/View/Welcome/LoginSubViews/TextLabelWithHyperlink.swift
  Sofa/Sources/View/Welcome/LoginView.swift
Labels: 🥕 로그인

#115 [FEAT] 사진/녹음 업로드 API
  Sofa.xcodeproj/project.pbxproj
  Sofa/Sources/Models/UploadFile.swift
  Sofa/Sources/Network/UploadManager.swift
  Sofa/Sources/View/Album/AlbumPhotoAddView/AlbumPhotoAddView.swift
  Sofa/Sources/View/Album/AlbumRecordAddView/AlbumRecordAddView.swift
  Sofa/Sources/View/Album/AlbumRecordAddView/SubViews/NavigationBar/AlbumRecordNavigationBar.swift
  Sofa/Sources/View/Album/AlbumRecordAddView/SubViews/ViewModel/AudioRecorderViewModel.swift
  Sofa/Sources/View/Album/AlbumRecordDetailView/AlbumRecordDetailView.swift
  Sofa/Sources/View/Album/AlbumSelectDateView/AlbumSelectDateView.swift
  Sofa/Sources/View/Album/AlbumSelectDateView/SubViews/ViewModel/AlbumUploadViewModel.swift
  Sofa/Sources/View/Album/AlbumSelectDateView/SubViews/ViewModel/AudioRecorderURLViewModel.swift
  Sofa/Sources/View/Album/AlbumView.swift
  Sofa/Sources/View/Album/SubViews/CameraImagePicker/CameraImagePicker.swift
Labels: 🏞 앨범, 📡 API

#117 [FEAT] 녹음 재생/정지
  Sofa/Sources/View/Album/AlbumRecordAddView/AlbumRecordAddView.swift
  Sofa/Sources/View/Album/AlbumRecordAddView/SubViews/ViewModel/AudioRecorderViewModel.swift
Labels: 🏞 앨범

#120 [CHORE] HomeView Detail 수정
  Sofa/Sources/View/Home/HomeView.swift
  Sofa/Sources/View/Home/SubViews/ChatList.swift
  Sofa/Sources/View/Home/SubViews/EventList.swift
  Sofa/Sources/View/Home/SubViews/Row/ChatRow.swift
Labels: 🏠 홈

#122 [FEAT] Splash Screen 및 Apple Login Logo
  Sofa.xcodeproj/project.pbxproj
  Sofa/Configuration/Assets/113766-gravity.json
  Sofa/Configuration/Assets/15025-bed.json
  Sofa/SofaApp.swift
  Sofa/Sources/View/Welcome/LoginSubViews/LoginButtonView.swift
  Sofa/Sources/View/Welcome/LoginSubViews/LoginViewModel/LoginViewModel.swift
  Sofa/Sources/View/Welcome/LoginSubViews/LottieView.swift
  Sofa/Sources/View/Welcome/LoginSubViews/SignInWithAppleButtonView.swift
  Sofa/Sources/View/Welcome/LoginView.swift
Labels: 🥕 로그인

#124 [FEAT] 설정탭과 프로필설정 구현
  Sofa/Configuration/Assets/Assets.xcassets/Register/Contents.json
  Sofa/Configuration/Assets/Assets.xcassets/Register/cta.imageset/Contents.json
  Sofa/Configuration/Assets/Assets.xcassets/Register/cta.imageset/cta.png
  Sofa/Configuration/Assets/Assets.xcassets/Register/cta.imageset/cta@2x.png
  Sofa/Configuration/Assets/Assets.xcassets/Register/cta.imageset/cta@3x.png
  Sofa/Configuration/Assets/Assets.xcassets/Register/goRoomBtn.imageset/Contents.json
  Sofa/Configuration/Assets/Assets.xcassets/Register/goRoomBtn.imageset/goRoomBtn.png
  Sofa/Configuration/Assets/Assets.xcassets/Register/goRoomBtn.imageset/goRoomBtn@2x.png
  Sofa/Configuration/Assets/Assets.xcassets/Register/goRoomBtn.imageset/goRoomBtn@3x.png
  Sofa/Configuration/Assets/Assets.xcassets/Register/linkBtn.imageset/Contents.json
  Sofa/Configuration/Assets/Assets.xcassets/Register/linkBtn.imageset/linkBtn.png
  Sofa/Configuration/Assets/Assets.xcassets/Register/linkBtn.imageset/linkBtn@2x.png
  Sofa/Configuration/Assets/Assets.xcassets/Register/linkBtn.imageset/linkBtn@3x.png
  Sofa/Configuration/Assets/Assets.xcassets/Register/profileFrame.imageset/Contents.json
  Sofa/Configuration/Assets/Assets.xcassets/Register/profileFrame.imageset/profileFrame.png
  Sofa/Configuration/Assets/Assets.xcassets/Register/profileFrame.imageset/profileFrame@2x.png
  Sofa/Configuration/Assets/Assets.xcassets/Register/profileFrame.imageset/profileFrame@3x.png
  Sofa/SofaApp.swift
  Sofa/Sources/View/Settings/SettingsView.swift
  Sofa/Sources/View/Settings/SubViews/ProfileSettingView.swift
Labels: ⚙️ 설정

#127 [FEAT] 설정 기능
  Sofa.xcodeproj/project.pbxproj
  Sofa/Sources/View/ContentView.swift
  Sofa/Sources/View/Home/HomeView.swift
  Sofa/Sources/View/Home/NotificationView.swift
  Sofa/Sources/View/Settings/SettingsView.swift
  Sofa/Sources/View/Settings/SubViews/InviteFamilyView.swift
  Sofa/Sources/View/Settings/SubViews/SetNotificationView.swift
  Sofa/Sources/View/Settings/SubViews/SettingRow.swift
Labels: ⚙️ 설정

#128 [FEAT] 앨범 상세 API 및 Refactor
  Sofa.xcodeproj/project.pbxproj
  Sofa/Configuration/Extensions/Ex+String.swift
  Sofa/Configuration/Mock/MockData.swift
  Sofa/Configuration/ViewModifiers/NavigationBarWithTextButtonStyle.swift
  Sofa/Sources/Models/Album.swift
  Sofa/Sources/Models/AlbumDetail.swift
  Sofa/Sources/Network/AlbumDetailManger.swift
  Sofa/Sources/View/Album/AlbumDetailView/AlbumDetailView.swift
  Sofa/Sources/View/Album/AlbumDetailView/SubViews/Row/AlbumDetailList.swift
  Sofa/Sources/View/Album/AlbumDetailView/SubViews/Row/AlbumDetailRow.swift
  Sofa/Sources/View/Album/AlbumDetailView/SubViews/ViewModel/AlbumDetailListCellViewModel.swift
  Sofa/Sources/View/Album/AlbumDetailView/SubViews/ViewModel/AlbumDetailListViewModel.swift
  Sofa/Sources/View/Album/AlbumEditView/AlbumDateEditView.swift
  Sofa/Sources/View/Album/AlbumEditView/AlbumTitleEditView.swift
  Sofa/Sources/View/Album/AlbumEditView/SubViews/NavigationBar/AlbumTitleEditNavigationBar.swift
  Sofa/Sources/View/Album/AlbumEditView/SubViews/ViewModel/AlbumEditViewModel.swift
  Sofa/Sources/View/Album/AlbumImageDetailView/AlbumImageDetailView.swift
  Sofa/Sources/View/Album/AlbumImageDetailView/SubViews/SettingBar/AlbumImageDetailSettingBar.swift
  Sofa/Sources/View/Album/AlbumRecordDetailView/AlbumRecordDetailView.swift
  Sofa/Sources/View/Album/AlbumSelectDateView/AlbumSelectDateView.swift
  Sofa/Sources/View/Album/AlbumSelectDateView/SubViews/ViewModel/AlbumUploadViewModel.swift
  Sofa/Sources/View/Album/SubViews/Row/AlbumDateRow.swift
  Sofa/Sources/View/Album/SubViews/Row/AlbumKindRow.swift
  Sofa/Sources/View/Album/SubViews/Row/AlbumList.swift
  Sofa/Sources/View/Album/SubViews/ScrollViewHelper/PullToRefresh.swift
  Sofa/Sources/View/Album/SubViews/ViewModel/AlbumListViewModel.swift
  Sofa/Sources/View/Album/SubViews/ViewModel/AuthorizationViewModel.swift
Labels: 🏞 앨범, 🐛Bug, 📡 API

#130 [FEAT] 댓글 API
  Sofa.xcodeproj/project.pbxproj
  Sofa/Sources/Models/Comment.swift
  Sofa/Sources/Network/CommentManger.swift
  Sofa/Sources/View/Album/AlbumCommentView/AlbumCommentView.swift
  Sofa/Sources/View/Album/AlbumCommentView/SubViews/CommentModal/CommentModal.swift
  Sofa/Sources/View/Album/AlbumCommentView/SubViews/Row/AlbumCommentList.swift
  Sofa/Sources/View/Album/AlbumCommentView/SubViews/Row/AlbumCommentRow.swift
  Sofa/Sources/View/Album/AlbumCommentView/SubViews/ViewModel/CommentViewModel.swift
  Sofa/Sources/View/Album/AlbumImageDetailView/AlbumImageDetailView.swift
  Sofa/Sources/View/Album/AlbumRecordDetailView/AlbumRecordDetailView.swift
  Sofa/Sources/View/Home/HomeView.swift
  Sofa/Sources/View/Home/MessageView.swift
Labels: 🏞 앨범, 📡 API

#133 [FIX] 앨범 API Update UI + 녹음 다운로드
  Sofa/Configuration/ViewModifiers/NavigationBarWithTextButtonStyle.swift
  Sofa/Sources/Models/AlbumDetail.swift
  Sofa/Sources/Network/AlbumDetailManger.swift
  Sofa/Sources/View/Album/AlbumCommentView/SubViews/Row/AlbumCommentList.swift
  Sofa/Sources/View/Album/AlbumDetailView/AlbumDetailView.swift
  Sofa/Sources/View/Album/AlbumDetailView/SubViews/Row/AlbumDetailList.swift
  Sofa/Sources/View/Album/AlbumDetailView/SubViews/Row/AlbumDetailRow.swift
  Sofa/Sources/View/Album/AlbumDetailView/SubViews/ViewModel/AlbumDetailListViewModel.swift
  Sofa/Sources/View/Album/AlbumRecordAddView/SubViews/ViewModel/AudioRecorderViewModel.swift
  Sofa/Sources/View/Album/AlbumView.swift
  Sofa/Sources/View/Album/SubViews/Authorization/PhotoAlbumAuthorization.swift
  Sofa/Sources/View/Album/SubViews/Row/AlbumList.swift
  Sofa/Sources/View/Album/SubViews/ViewModel/AlbumListViewModel.swift
  Sofa/Sources/View/Album/SubViews/ViewModel/AuthorizationViewModel.swift
Labels: 🏞 앨범, 🐛Bug, 📡 API

#134 [FEAT] Setting UI & 알림 연결
  Sofa.xcodeproj/project.pbxproj
  Sofa/Configuration/Assets/Assets.xcassets/Setting/Contents.json
  Sofa/Configuration/Assets/Assets.xcassets/Setting/checkmark.circle.fill.imageset/Contents.json
  Sofa/Configuration/Assets/Assets.xcassets/Setting/checkmark.circle.fill.imageset/checkmark.circle.fill.png
  Sofa/Configuration/Assets/Assets.xcassets/Setting/checkmark.circle.fill.imageset/checkmark.circle.fill@2x.png
  Sofa/Configuration/Assets/Assets.xcassets/Setting/checkmark.circle.fill.imageset/checkmark.circle.fill@3x.png
  Sofa/Configuration/Assets/Assets.xcassets/Setting/checkmark.circle.imageset/Contents.json
  Sofa/Configuration/Assets/Assets.xcassets/Setting/checkmark.circle.imageset/checkmark.circle.png
  Sofa/Configuration/Assets/Assets.xcassets/Setting/checkmark.circle.imageset/checkmark.circle@2x.png
  Sofa/Configuration/Assets/Assets.xcassets/Setting/checkmark.circle.imageset/checkmark.circle@3x.png
  Sofa/Configuration/Assets/Assets.xcassets/Setting/info.circle.fill.imageset/Contents.json
  Sofa/Configuration/Assets/Assets.xcassets/Setting/info.circle.fill.imageset/info.circle.fill.png
  Sofa/Configuration/Assets/Assets.xcassets/Setting/info.circle.fill.imageset/info.circle.fill@2x.png
  Sofa/Configuration/Assets/Assets.xcassets/Setting/info.circle.fill.imageset/info.circle.fill@3x.png
  Sofa/Configuration/Mock/ChatInfoMock.json
  Sofa/SofaApp.swift
  Sofa/Sources/View/Home/HomeView.swift
  Sofa/Sources/View/Home/MessageView.swift
  Sofa/Sources/View/Home/SubViews/Row/ChatRow.swift
  Sofa/Sources/View/Settings/SettingsView.swift
  Sofa/Sources/View/Settings/SubViews/AccountAndSecurityView.swift
  Sofa/Sources/View/Settings/SubViews/RevokeAccountView.swift
  Sofa/Sources/View/Settings/SubViews/SetNotificationView.swift
Labels: 🏠 홈, ⚙️ 설정

#137 [FEAT] 자동로그인 & 로그아웃 & Device 설정 & 버그 수정
  Sofa/Configuration/Base/Constants/Constants.swift
  Sofa/Info.plist
  Sofa/SofaApp.swift
  Sofa/Sources/View/Home/NotificationView.swift
  Sofa/Sources/View/Settings/SettingsView.swift
  Sofa/Sources/View/Settings/SubViews/AccountAndSecurityView.swift
Labels: 🥕 로그인, 🐛Bug, ⚙️ 설정

#139 [FEAT] 가족설정뷰 UI
  Sofa.xcodeproj/project.pbxproj
  Sofa/Configuration/Extensions/Ex+Date.swift
  Sofa/Sources/View/Calendar/SubViews/CustomDatePicker.swift
  Sofa/Sources/View/Calendar/SubViews/GeneralCalendar.swift
  Sofa/Sources/View/Settings/SettingsView.swift
  Sofa/Sources/View/Settings/SubViews/FamilySettingView.swift
  Sofa/Sources/View/Settings/SubViews/ProfileSettingView.swift
  Sofa/Sources/View/Welcome/RegisterSubViews/RegisterFamilyFinishView.swift
Labels: ⚙️ 설정

#141 [FEAT] 로그인 -> 회원가입 -> 가족 생성
  Sofa/Sources/View/Settings/SettingsView.swift
  Sofa/Sources/View/Settings/SubViews/ProfileSettingView.swift
  Sofa/Sources/View/Welcome/LoginSubViews/LoginButtonView.swift
  Sofa/Sources/View/Welcome/LoginSubViews/LoginViewModel/LoginViewModel.swift
  Sofa/Sources/View/Welcome/RegisterSubViews/RegisterFinishView.swift
  Sofa/Sources/View/Welcome/RegisterView.swift
  Sofa/Sources/View/Welcome/ViewModel/RegisterViewModel.swift
Labels: 🥕 로그인, 🌱 회원가입

#143 [FIX] Home Detail 수정
  Sofa/Configuration/Extensions/Ex+String.swift
  Sofa/SofaApp.swift
  Sofa/Sources/View/ContentView.swift
  Sofa/Sources/View/Home/HomeView.swift
  Sofa/Sources/View/Home/MessageView.swift
  Sofa/Sources/View/Home/SubViews/EmojiView.swift
  Sofa/Sources/View/Home/SubViews/EventList.swift
Labels: 🏠 홈

#145 [FEAT] 설정뷰의 유저 정보 조회
  Sofa.xcodeproj/project.pbxproj
  Sofa/Configuration/Extensions/Ex+View.swift
  Sofa/Sources/Models/CalendarTask.swift
  Sofa/Sources/Models/RegisterUser.swift
  Sofa/Sources/Network/RegisterManager.swift
  Sofa/Sources/View/Calendar/SubViews/AppendTaskModalView.swift
  Sofa/Sources/View/Calendar/SubViews/Task/AppendTaskModalView.swift
  Sofa/Sources/View/Calendar/SubViews/Task/TaskColorPicker.swift
  Sofa/Sources/View/Calendar/SubViews/Task/TaskDetailView.swift
  Sofa/Sources/View/Calendar/SubViews/Task/TaskMetaData.swift
  Sofa/Sources/View/Calendar/SubViews/Task/TaskTimePicker.swift
  Sofa/Sources/View/Calendar/SubViews/TaskDetailView.swift
  Sofa/Sources/View/Calendar/TaskMetaData.swift
  Sofa/Sources/View/Settings/SettingsView.swift
  Sofa/Sources/View/Settings/ViewModel/SettingViewModel.swift
Labels: ⚙️ 설정, 📡 API

#148 [FEAT] 회원가입의 가족 생성과 유저 정보 수정 API 연결
  Sofa.xcodeproj/project.pbxproj
  Sofa/Sources/Models/RegisterUser.swift
  Sofa/Sources/Models/UserPatchResponse.swift
  Sofa/Sources/Network/UserFamilyManager.swift
  Sofa/Sources/View/Settings/SubViews/ProfileSettingView.swift
  Sofa/Sources/View/Settings/ViewModel/SettingViewModel.swift
  Sofa/Sources/View/Welcome/RegisterFamilyView.swift
  Sofa/Sources/View/Welcome/RegisterView.swift
  Sofa/Sources/View/Welcome/ViewModel/RegisterFamilyViewModel.swift
  Sofa/Sources/View/Welcome/ViewModel/RegisterViewModel.swift
Labels: 🌱 회원가입, 📡 API
