Repository YAPP-Github/20th-iOS-Team-2-FE, pull requests merged in 2022-08, with the labels that each got.

#150 [CHORE] Album UI 전체적인 수정
  Sofa.xcodeproj/project.pbxproj
  Sofa/Configuration/Assets/Assets.xcassets/Photo/empty1.imageset/Contents.json
  Sofa/Configuration/Assets/Assets.xcassets/Photo/empty1.imageset/empty1.png
  Sofa/Configuration/Assets/Assets.xcassets/Photo/empty1.imageset/empty1@2x.png
  Sofa/Configuration/Assets/Assets.xcassets/Photo/empty1.imageset/empty1@3x.png
  Sofa/Configuration/Assets/Assets.xcassets/Photo/empty2.imageset/Contents.json
  Sofa/Configuration/Assets/Assets.xcassets/Photo/empty2.imageset/empty2.png
  Sofa/Configuration/Assets/Assets.xcassets/Photo/empty2.imageset/empty2@2x.png
  Sofa/Configuration/Assets/Assets.xcassets/Photo/empty2.imageset/empty2@3x.png
  Sofa/Configuration/Assets/Assets.xcassets/Photo/empty3.imageset/Contents.json
  Sofa/Configuration/Assets/Assets.xcassets/Photo/empty3.imageset/empty3.png
  Sofa/Configuration/Assets/Assets.xcassets/Photo/empty3.imageset/empty3@2x.png
  Sofa/Configuration/Assets/Assets.xcassets/Photo/empty3.imageset/empty3@3x.png
  Sofa/Configuration/ViewModifiers/ToastMessage.swift
  Sofa/Info.plist
  Sofa/Sources/Models/Album.swift
  Sofa/Sources/Models/Comment.swift
  Sofa/Sources/View/Album/AlbumCommentView/AlbumCommentView.swift
  Sofa/Sources/View/Album/AlbumCommentView/SubViews/CommentModal/CommentModal.swift
  Sofa/Sources/View/Album/AlbumCommentView/SubViews/Row/AlbumCommentList.swift
  Sofa/Sources/View/Album/AlbumCommentView/SubViews/Row/AlbumCommentRow.swift
  Sofa/Sources/View/Album/AlbumCommentView/SubViews/ViewModel/CommentViewModel.swift
  Sofa/Sources/View/Album/AlbumDetailView/AlbumDetailView.swift
  Sofa/Sources/View/Album/AlbumDetailView/SubViews/Row/AlbumDetailList.swift
  Sofa/Sources/View/Album/AlbumDetailView/SubViews/Row/AlbumDetailRow.swift
  Sofa/Sources/View/Album/AlbumEditView/AlbumDateEditView.swift
  Sofa/Sources/View/Album/AlbumEditView/AlbumTitleEditView.swift
  Sofa/Sources/View/Album/AlbumImageDetailView/AlbumImageDetailView.swift
  Sofa/Sources/View/Album/AlbumImageDetailView/SubViews/SettingBar/AlbumImageDetailSettingBar.swift
  Sofa/Sources/View/Album/AlbumRecordAddView/AlbumRecordAddView.swift
  Sofa/Sources/View/Album/AlbumRecordAddView/SubViews/ViewModel/AudioRecorderViewModel.swift
  Sofa/Sources/View/Album/AlbumRecordDetailView/AlbumRecordDetailView.swift
  Sofa/Sources/View/Album/AlbumSelectDateView/AlbumSelectDateView.swift
  Sofa/Sources/View/Album/AlbumSelectDateView/SubViews/ViewModel/AlbumUploadViewModel.swift
  Sofa/Sources/View/Album/AlbumView.swift
  Sofa/Sources/View/Album/SubViews/ActionSheet/AlbumActionSheetCard.swift
  Sofa/Sources/View/Album/SubViews/Row/AlbumDateRow.swift
  Sofa/Sources/View/Album/SubViews/Row/AlbumList.swift
  Sofa/Sources/View/Home/HomeView.swift
  Sofa/Sources/View/Home/MessageView.swift
Labels: 🏞 앨범, 🐛Bug, 📡 API

#152 [CHORE] Navigation Bar 및 History 대응
  Sofa/Sources/View/ContentView.swift
  Sofa/Sources/View/Home/HistoryView.swift
  Sofa/Sources/View/Home/HomeView.swift
  Sofa/Sources/View/Home/NotificationView.swift
  Sofa/Sources/View/Home/SubViews/HomeNavigationBarStyle.swift
  Sofa/Sources/View/Settings/SubViews/AccountAndSecurityView.swift
  Sofa/Sources/View/Settings/SubViews/RevokeAccountView.swift
  Sofa/Sources/View/Settings/SubViews/SetNotificationView.swift
Labels: 🏠 홈, ⚙️ 설정

#155 [FEAT] Login 테스트 및 user ID 저장
  Sofa.xcodeproj/project.pbxproj
  Sofa/Configuration/Base/Constants/Constants.swift
  Sofa/SofaApp.swift
  Sofa/Sources/Models/LoginResponse.swift
  Sofa/Sources/View/Home/HomeView.swift
  Sofa/Sources/View/Settings/SubViews/AccountAndSecurityView.swift
  Sofa/Sources/View/Welcome/LoginSubViews/LoginButtonView.swift
  Sofa/Sources/View/Welcome/LoginSubViews/LoginViewModel/LoginViewModel.swift
  Sofa/Sources/View/Welcome/RegisterSubViews/RegisterFinishView.swift
  Sofa/Sources/View/Welcome/RegisterView.swift
Labels: 🥕 로그인

#153 [FEAT] Chat 웹소켓 연결
  Sofa.xcodeproj/project.pbxproj
  Sofa.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Sofa/Sources/Models/NewChatResponse.swift
  Sofa/Sources/Models/OriginalChatResponse.swift
  Sofa/Sources/View/Home/Chat.swift
  Sofa/Sources/View/Home/ChatScreenViewModel.swift
  Sofa/Sources/View/Home/HomeView.swift
  Sofa/Sources/View/Home/StarscreamWebsocket.swift
  Sofa/Sources/View/Home/SubViews/ChatList.swift
  Sofa/Sources/View/Home/SubViews/Row/ChatRow.swift
Labels: 🏠 홈

#159 [FIX] 무한 회원가입 방지
  Sofa.xcodeproj/project.pbxproj
  Sofa/Configuration/Extensions/Ex+String.swift
  Sofa/Sources/Models/CalendarTask.swift
  Sofa/Sources/Network/UserFamilyManager.swift
  Sofa/Sources/View/Calendar/SubViews/ColorCircles.swift
  Sofa/Sources/View/Calendar/SubViews/CustomDatePicker.swift
  Sofa/Sources/View/Calendar/SubViews/Task/AppendTaskModalView.swift
  Sofa/Sources/View/Calendar/SubViews/Task/TaskCell.swift
  Sofa/Sources/View/Calendar/SubViews/Task/TaskColorPicker.swift
  Sofa/Sources/View/Calendar/SubViews/Task/TaskDetailView.swift
  Sofa/Sources/View/Calendar/SubViews/Task/TaskMetaData.swift
  Sofa/Sources/View/Calendar/SubViews/Task/TaskStore.swift
  Sofa/Sources/View/Calendar/SubViews/Task/TaskTimePicker.swift
  Sofa/Sources/View/ContentView.swift
  Sofa/Sources/View/Settings/SettingsView.swift
  Sofa/Sources/View/Settings/ViewModel/SettingViewModel.swift
  Sofa/Sources/View/Welcome/ViewModel/RegisterViewModel.swift
Labels: 🌱 회원가입, 🐛Bug

#161 [CHORE] Acess token
  Sofa/Configuration/Base/Constants/Constants.swift
  Sofa/Sources/Models/Album.swift
  Sofa/Sources/Network/AlbumDetailManger.swift
  Sofa/Sources/Network/CommentManger.swift
  Sofa/Sources/View/Album/AlbumCommentView/SubViews/CommentModal/CommentModal.swift
  Sofa/Sources/View/Album/AlbumCommentView/SubViews/Row/AlbumCommentRow.swift
  Sofa/Sources/View/Album/AlbumCommentView/SubViews/ViewModel/CommentViewModel.swift
  Sofa/Sources/View/Album/AlbumDetailView/AlbumDetailView.swift
  Sofa/Sources/View/Album/AlbumDetailView/SubViews/ViewModel/AlbumDetailListViewModel.swift
  Sofa/Sources/View/Album/AlbumEditView/AlbumDateEditView.swift
  Sofa/Sources/View/Album/AlbumImageDetailView/AlbumImageDetailView.swift
  Sofa/Sources/View/Album/AlbumImageDetailView/SubViews/NavigaionBar/AlbumImageDetailNavigationBar.swift
  Sofa/Sources/View/Album/AlbumImageDetailView/SubViews/SettingBar/AlbumImageDetailSettingBar.swift
  Sofa/Sources/View/Album/AlbumPhotoAddView/AlbumPhotoAddView.swift
  Sofa/Sources/View/Album/AlbumRecordAddView/AlbumRecordAddView.swift
  Sofa/Sources/View/Album/AlbumRecordAddView/SubViews/NavigationBar/AlbumRecordNavigationBar.swift
  Sofa/Sources/View/Album/AlbumRecordDetailView/AlbumRecordDetailView.swift
  Sofa/Sources/View/Album/AlbumSelectDateView/AlbumSelectDateView.swift
  Sofa/Sources/View/Album/AlbumView.swift
  Sofa/Sources/View/Album/SubViews/Row/AlbumList.swift
Labels: 🏞 앨범, 🐛Bug

#162 [FEAT] 초대 코드 입력 뷰 구현
  Sofa.xcodeproj/project.pbxproj
  Sofa/Configuration/Assets/Assets.xcassets/Register/code.imageset/Contents.json
  Sofa/Configuration/Assets/Assets.xcassets/Register/code.imageset/code.png
  Sofa/Configuration/Assets/Assets.xcassets/Register/code.imageset/code@2x.png
  Sofa/Configuration/Assets/Assets.xcassets/Register/code.imageset/code@3x.png
  Sofa/SofaApp.swift
  Sofa/Sources/Models/UserFamily.swift
  Sofa/Sources/Models/UserFamilyPatchResponse.swift
  Sofa/Sources/Network/UserFamilyManager.swift
  Sofa/Sources/View/Settings/SettingsView.swift
  Sofa/Sources/View/Settings/ViewModel/SettingViewModel.swift
  Sofa/Sources/View/Welcome/RegisterSubViews/EnterCodeView.swift
  Sofa/Sources/View/Welcome/RegisterSubViews/RegisterFamilyFinishView.swift
  Sofa/Sources/View/Welcome/RegisterSubViews/RegisterFinishView.swift
  Sofa/Sources/View/Welcome/RegisterView.swift
Labels: 🌱 회원가입

#163 [FEAT] 캘린더 일정 생성, 수정 로직 변경
  Sofa/Sources/View/Calendar/SubViews/ColorCircles.swift
  Sofa/Sources/View/Calendar/SubViews/Task/AppendTaskModalView.swift
  Sofa/Sources/View/Calendar/SubViews/Task/TaskCell.swift
  Sofa/Sources/View/Calendar/SubViews/Task/TaskColorPicker.swift
  Sofa/Sources/View/Calendar/SubViews/Task/TaskDetailView.swift
  Sofa/Sources/View/Calendar/SubViews/Task/TaskStore.swift
  Sofa/Sources/View/Calendar/SubViews/Task/TaskTimePicker.swift
Labels: 📅 캘린더

#164 [FEAT] Acess token
  Sofa/Sources/Models/Comment.swift
  Sofa/Sources/Network/AlbumDetailManger.swift
  Sofa/Sources/Network/AlbumManager.swift
  Sofa/Sources/Network/CommentManger.swift
  Sofa/Sources/Network/UploadManager.swift
  Sofa/Sources/View/Album/AlbumCommentView/SubViews/Row/AlbumCommentRow.swift
  Sofa/Sources/View/Album/AlbumCommentView/SubViews/ViewModel/CommentViewModel.swift
Labels: 🏞 앨범
