Repository YAPP-Github/20th-iOS-Team-2-FE, pull requests merged in 2022-06, with the labels that each got.

#27 [FEAT] 로그인 Initial UI & Animation
  Podfile
  Podfile.lock
  Sofa.xcodeproj/project.pbxproj
  Sofa/Configuration/Assets/15025-bed.json
  Sofa/Configuration/Assets/Assets.xcassets/SignInWithApple.imageset/Contents.json
  Sofa/Configuration/Assets/Assets.xcassets/SignInWithApple.imageset/SignInWithApple.png
  Sofa/Configuration/Assets/Assets.xcassets/SignInWithkakao.imageset/Contents.json
  Sofa/Configuration/Assets/Assets.xcassets/SignInWithkakao.imageset/SignInWithkakao.png
  Sofa/Configuration/Assets/Assets.xcassets/kakao_login_medium_narrow.imageset/kakao_login_medium_narrow.png
  Sofa/Configuration/Assets/Assets.xcassets/line.imageset/Contents.json
  Sofa/Configuration/Assets/Assets.xcassets/line.imageset/line.png
  Sofa/Configuration/Extensions/View.swift
  Sofa/Sources/View/Welcome/LoginSubViews/LoginButtonView.swift
  Sofa/Sources/View/Welcome/LoginSubViews/LottieView.swift
  Sofa/Sources/View/Welcome/LoginView.swift
Labels: 🥕 로그인

#13 [Feat] 3-album/by DateTab
  Sofa.xcodeproj/project.pbxproj
  Sofa/Configuration/Extensions/Ex+Color.swift
  Sofa/Sources/Models/Album.swift
  Sofa/Sources/View/Album/AlbumView.swift
  Sofa/Sources/View/Album/SubViews/AlbumDetailView/AlbumDetailView.swift
  Sofa/Sources/View/Album/SubViews/NavigationBar/NavigationBarWithButton.swift
  Sofa/Sources/View/Album/SubViews/Row/AlbumList.swift
  Sofa/Sources/View/Album/SubViews/Row/AlbumRow.swift
  Sofa/Sources/View/ContentView.swift
Labels: 🏞 앨범

#15 [FEAT] Album의 Plus 눌러서 ActionSheet 띄우기
  Sofa.xcodeproj/project.pbxproj
  Sofa/Configuration/Extensions/Ex+UITabBar.swift
  Sofa/Configuration/Extensions/Ex+UIView.swift
  Sofa/Configuration/Extensions/Ex+View.swift
  Sofa/Configuration/Extensions/Extensions.swift
  Sofa/Configuration/ViewModifiers/HiddenTabBar.swift
  Sofa/Configuration/ViewModifiers/ShowTabBar.swift
  Sofa/Sources/Models/Models.swift
  Sofa/Sources/View/Album/AlbumView.swift
  Sofa/Sources/View/Album/SubViews/ActionSheet/AlbumActionSheetCard.swift
  Sofa/Sources/View/Album/SubViews/ActionSheet/AlbumActionSheetItem.swift
  Sofa/Sources/View/Album/SubViews/ActionSheet/GreyOutOfFocusView.swift
  Sofa/Sources/View/Album/SubViews/AlbumAddView/AlbumPhotoAddView.swift
  Sofa/Sources/View/Album/SubViews/AlbumAddView/AlbumRecordAddView.swift
  Sofa/Sources/View/Album/SubViews/NavigationBar/NavigationBarWithButton.swift
  Sofa/Sources/View/ContentView.swift
Labels: 🏞 앨범

#25 [FEAT] Album 유형별 Row & Album Detail View
  Sofa.xcodeproj/project.pbxproj
  Sofa/Configuration/Base/Constants/Constants.swift
  Sofa/Configuration/Extensions/Ex+Color.swift
  Sofa/Configuration/Extensions/Ex+Date.swift
  Sofa/Configuration/Extensions/Ex+UITabBar.swift
  Sofa/Configuration/Extensions/Ex+View.swift
  Sofa/Configuration/Mock/MockData.swift
  Sofa/Configuration/ViewModifiers/NavigationBarWithIconButtonStyle.swift
  Sofa/Configuration/ViewModifiers/NavigationBarWithTextButtonStyle.swift
  Sofa/Configuration/ViewModifiers/PinchToZoom.swift
  Sofa/Sources/Models/Album.swift
  Sofa/Sources/Models/AlbumDetail.swift
  Sofa/Sources/Models/AlbumType.swift
  Sofa/Sources/View/Album/AlbumView.swift
  Sofa/Sources/View/Album/SubViews/ActionSheet/AlbumActionSheetCard.swift
  Sofa/Sources/View/Album/SubViews/ActionSheet/GreyOutOfFocusView.swift
  Sofa/Sources/View/Album/SubViews/AlbumAddView/AlbumPhotoAddView/AlbumPhotoAddView.swift
  Sofa/Sources/View/Album/SubViews/AlbumAddView/AlbumPhotoAddView/SubViews/Row/AlbumPhotoAddList.swift
  Sofa/Sources/View/Album/SubViews/AlbumAddView/AlbumPhotoAddView/SubViews/Row/AlbumPhotoAddRow.swift
  Sofa/Sources/View/Album/SubViews/AlbumAddView/AlbumPhotoAddView/SubViews/Row/AlbumPhotoLibrary.swift
  Sofa/Sources/View/Album/SubViews/AlbumAddView/AlbumRecordAddView/AlbumRecordAddView.swift
  Sofa/Sources/View/Album/SubViews/AlbumDetailView/AlbumDetailView.swift
  Sofa/Sources/View/Album/SubViews/AlbumDetailView/SubViews/Row/AlbumDetailList.swift
  Sofa/Sources/View/Album/SubViews/AlbumDetailView/SubViews/Row/AlbumDetailRow.swift
  Sofa/Sources/View/Album/SubViews/AlbumSelectDateView/AlbumSelectDateView.swift
  Sofa/Sources/View/Album/SubViews/Row/AlbumList.swift
  Sofa/Sources/View/Album/SubViews/Row/AlbumRow.swift
  Sofa/Sources/View/Album/SubViews/Row/AlbumTypeRow.swift
  Sofa/Sources/View/ContentView.swift
Labels: 🏞 앨범

#32 [FEAT] SwiftKeychainWrapper 적용
  Podfile
  Podfile.lock
  Sofa/SofaApp.swift
  Sofa/Sources/View/Welcome/LoginSubViews/LoginButtonView.swift
Labels: 🥕 로그인

#33 [FEAT] Login UI Detail
  Sofa.xcodeproj/project.pbxproj
  Sofa/Configuration/Extensions/Ex+Color.swift
  Sofa/Configuration/Extensions/Ex+Font.swift
  Sofa/Configuration/Extensions/Ex+UIColor.swift
  Sofa/Configuration/Extensions/Ex+UIDevice.swift
  Sofa/Configuration/Extensions/View.swift
  Sofa/Configuration/Fonts/LibreBaskerville-Bold.ttf
  Sofa/Configuration/Fonts/LibreBaskerville-Regular.ttf
  Sofa/Configuration/Fonts/Pretendard-Black.otf
  Sofa/Configuration/Fonts/Pretendard-Bold.otf
  Sofa/Configuration/Fonts/Pretendard-ExtraBold.otf
  Sofa/Configuration/Fonts/Pretendard-ExtraLight.otf
  Sofa/Configuration/Fonts/Pretendard-Light.otf
  Sofa/Configuration/Fonts/Pretendard-Medium.otf
  Sofa/Configuration/Fonts/Pretendard-Regular.otf
  Sofa/Configuration/Fonts/Pretendard-SemiBold.otf
  Sofa/Configuration/Fonts/Pretendard-Thin.otf
  Sofa/Info.plist
  Sofa/SofaApp.swift
  Sofa/Sources/View/Welcome/LoginSubViews/CustomText.swift
  Sofa/Sources/View/Welcome/LoginSubViews/LoginButtonView.swift
  Sofa/Sources/View/Welcome/LoginSubViews/LottieView.swift
  Sofa/Sources/View/Welcome/LoginView.swift
Labels: 🥕 로그인

#38 [FEAT] 일정 View UI
  Sofa.xcodeproj/project.pbxproj
  Sofa/Configuration/Assets/Assets.xcassets/Event/Contents.json
  Sofa/Configuration/Assets/Assets.xcassets/Event/birthday.imageset/Contents.json
  Sofa/Configuration/Assets/Assets.xcassets/Event/birthday.imageset/birthday.png
  Sofa/Configuration/Assets/Assets.xcassets/Event/birthday.imageset/birthday@2x.png
  Sofa/Configuration/Assets/Assets.xcassets/Event/birthday.imageset/birthday@3x.png
  Sofa/Configuration/Assets/Assets.xcassets/Event/greencolorIcon.imageset/Contents.json
  Sofa/Configuration/Assets/Assets.xcassets/Event/greencolorIcon.imageset/greencolorIcon.png
  Sofa/Configuration/Assets/Assets.xcassets/Event/greencolorIcon.imageset/greencolorIcon@2x.png
  Sofa/Configuration/Assets/Assets.xcassets/Event/greencolorIcon.imageset/greencolorIcon@3x.png
  Sofa/Configuration/Assets/Assets.xcassets/Event/x.circle.fill.imageset/Contents.json
  Sofa/Configuration/Assets/Assets.xcassets/Event/x.circle.fill.imageset/x.circle.fill.png
  Sofa/Configuration/Assets/Assets.xcassets/Event/x.circle.fill.imageset/x.circle.fill@2x.png
  Sofa/Configuration/Assets/Assets.xcassets/Event/x.circle.fill.imageset/x.circle.fill@3x.png
  Sofa/Configuration/Assets/Assets.xcassets/Login/Contents.json
  Sofa/Configuration/Assets/Assets.xcassets/Login/SignInWithApple.imageset/Contents.json
  Sofa/Configuration/Assets/Assets.xcassets/Login/SignInWithApple.imageset/SignInWithApple.png
  Sofa/Configuration/Assets/Assets.xcassets/Login/SignInWithApple.imageset/SignInWithApple@2x.png
  Sofa/Configuration/Assets/Assets.xcassets/Login/SignInWithApple.imageset/SignInWithApple@3x.png
  Sofa/Configuration/Assets/Assets.xcassets/Login/SignInWithkakao.imageset/Contents.json
  Sofa/Configuration/Assets/Assets.xcassets/Login/SignInWithkakao.imageset/SignInWithkakao.png
  Sofa/Configuration/Assets/Assets.xcassets/Login/SignInWithkakao.imageset/SignInWithkakao@2x.png
  Sofa/Configuration/Assets/Assets.xcassets/Login/SignInWithkakao.imageset/SignInWithkakao@3x.png
  Sofa/Configuration/Mock/HomeInfoMock.json
  Sofa/Configuration/ViewModifiers/NavigationBarWithIconButtonStyle.swift
  Sofa/SofaApp.swift
  Sofa/Sources/Models/HomeInfo.swift
  Sofa/Sources/View/Home/HomeView.swift
  Sofa/Sources/View/Home/SubViews/EventList.swift
  Sofa/Sources/View/Home/SubViews/Row/EventRow.swift
  Sofa/Sources/View/Home/ViewModel/EventViewModel.swift
Labels: 🏠 홈

#40 [FEAT] Camera & Recording
  Sofa.xcodeproj/project.pbxproj
  Sofa/Info.plist
  Sofa/Sources/View/Album/AlbumDetailView/AlbumDetailView.swift
  Sofa/Sources/View/Album/AlbumDetailView/SubViews/Row/AlbumDetailList.swift
  Sofa/Sources/View/Album/AlbumDetailView/SubViews/Row/AlbumDetailRow.swift
  Sofa/Sources/View/Album/AlbumPhotoAddView/AlbumPhotoAddView.swift
  Sofa/Sources/View/Album/AlbumPhotoAddView/SubViews/Row/AlbumPhotoAddList.swift
  Sofa/Sources/View/Album/AlbumPhotoAddView/SubViews/Row/AlbumPhotoAddRow.swift
  Sofa/Sources/View/Album/AlbumPhotoAddView/SubViews/Row/AlbumPhotoLibrary.swift
  Sofa/Sources/View/Album/AlbumPhotoAddView/SubViews/ZoomScrollView/ZoomScrollView.swift
  Sofa/Sources/View/Album/AlbumRecordAddView/AlbumRecordAddView.swift
  Sofa/Sources/View/Album/AlbumRecordAddView/SubViews/AudioBar/AudioBarView.swift
  Sofa/Sources/View/Album/AlbumRecordAddView/SubViews/NavigationBar/NavigationBarOnlyCancelButtonStyle.swift
  Sofa/Sources/View/Album/AlbumRecordAddView/SubViews/ViewModel/AudioRecorderViewModel.swift
  Sofa/Sources/View/Album/AlbumSelectDateView/AlbumSelectDateView.swift
  Sofa/Sources/View/Album/AlbumSelectDateView/SubViews/ViewModel/AudioRecorderURLViewModel.swift
  Sofa/Sources/View/Album/AlbumView.swift
  Sofa/Sources/View/Album/SubViews/ActionSheet/AlbumActionSheetCard.swift
  Sofa/Sources/View/Album/SubViews/AlbumAddView/AlbumRecordAddView/AlbumRecordAddView.swift
  Sofa/Sources/View/Album/SubViews/AlbumSelectDateView/AlbumSelectDateView.swift
  Sofa/Sources/View/Album/SubViews/Authorization/CameraAuthorization.swift
  Sofa/Sources/View/Album/SubViews/Authorization/PhotoAlbumAuthorization.swift
  Sofa/Sources/View/Album/SubViews/Authorization/RecordAuthorization.swift
  Sofa/Sources/View/Album/SubViews/CameraImagePicker/CameraImagePicker.swift
  Sofa/Sources/View/Album/SubViews/Row/AlbumList.swift
  Sofa/Sources/View/Album/SubViews/Row/AlbumRow.swift
  Sofa/Sources/View/Album/SubViews/Row/AlbumTypeRow.swift
  Sofa/Sources/View/Album/ViewModel/AuthorizationViewModel.swift
Labels: 🏞 앨범

#42 [FEAT] Toast Message
  Sofa.xcodeproj/project.pbxproj
  Sofa/Configuration/ViewModifiers/ToastMessage.swift
  Sofa/Sources/View/Album/AlbumPhotoAddView/AlbumPhotoAddView.swift
  Sofa/Sources/View/Album/AlbumPhotoAddView/SubViews/Row/AlbumPhotoAddList.swift
  Sofa/Sources/View/Album/AlbumPhotoAddView/SubViews/Row/AlbumPhotoAddRow.swift
Labels: 🏞 앨범

#45 [FEAT] 앨범 Detail View action sheet 와 디자인 수정
  Sofa/Configuration/ViewModifiers/NavigationBarWithIconButtonStyle.swift
  Sofa/Sources/View/Album/AlbumDetailView/AlbumDetailView.swift
  Sofa/Sources/View/Album/AlbumDetailView/SubViews/Row/AlbumDetailList.swift
  Sofa/Sources/View/Album/AlbumDetailView/SubViews/Row/AlbumDetailRow.swift
  Sofa/Sources/View/Album/AlbumPhotoAddView/AlbumPhotoAddView.swift
  Sofa/Sources/View/Album/AlbumView.swift
  Sofa/Sources/View/Album/SubViews/ActionSheet/AlbumActionSheetCard.swift
  Sofa/Sources/View/Album/SubViews/ActionSheet/AlbumActionSheetItem.swift
  Sofa/Sources/View/Home/SubViews/EventList.swift
Labels: 🏞 앨범

#37 [FEAT] 캘린더 달력 UI 구현
  Sofa.xcodeproj/project.pbxproj
  Sofa/Configuration/Extensions/Ex+Date.swift
  Sofa/Sources/View/Calendar/CalendarView.swift
  Sofa/Sources/View/Calendar/CustomDatePicker.swift
  Sofa/Sources/View/Calendar/DateValue.swift
  Sofa/Sources/View/Calendar/Task.swift
Labels: 📅 캘린더

#50 [FEAT] Chat UI 구현
  Sofa.xcodeproj/project.pbxproj
  Sofa.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Sofa/Configuration/Assets/Assets.xcassets/Chat/Contents.json
  Sofa/Configuration/Assets/Assets.xcassets/Chat/lionprofile.imageset/Contents.json
  Sofa/Configuration/Assets/Assets.xcassets/Chat/lionprofile.imageset/lionprofile.png
  Sofa/Configuration/Assets/Assets.xcassets/Chat/lionprofile.imageset/lionprofile@2x.png
  Sofa/Configuration/Assets/Assets.xcassets/Chat/lionprofile.imageset/lionprofile@3x.png
  Sofa/Configuration/Assets/Assets.xcassets/dividert.imageset/Contents.json
  Sofa/Configuration/Assets/Assets.xcassets/dividert.imageset/dividert.png
  Sofa/Configuration/Assets/Assets.xcassets/dividert.imageset/dividert@2x.png
  Sofa/Configuration/Assets/Assets.xcassets/dividert.imageset/dividert@3x.png
  Sofa/Sources/View/Home/HomeView.swift
  Sofa/Sources/View/Home/SubViews/ChatList.swift
  Sofa/Sources/View/Home/SubViews/EmojiView.swift
  Sofa/Sources/View/Home/SubViews/EventList.swift
  Sofa/Sources/View/Home/SubViews/LabelView.swift
  Sofa/Sources/View/Home/SubViews/Row/ChatRow.swift
  Sofa/Sources/View/Home/SubViews/Row/EventRow.swift
Labels: 🏠 홈, 🛠Needs Refactoring🛠

#48 [FEAT] 캘린더 Task UI 구현
  Sofa.xcodeproj/project.pbxproj
  Sofa/Configuration/Extensions/Ex+Date.swift
  Sofa/Sources/View/Calendar/CalendarView.swift
  Sofa/Sources/View/Calendar/CustomDatePicker.swift
  Sofa/Sources/View/Calendar/Task.swift
Labels: 📅 캘린더
